FCODE = {
    # VRI Version
    "vin01m.mul.html.txt": ["1", "Mūla > Vinayapiṭaka > Pārājikapāḷi", "Mūla > Vinayapiṭaka > Pārājikapāḷi [vin01m.mul.html.txt]"],
    "vin02m1.mul.html.txt": ["2", "Mūla > Vinayapiṭaka > Pācittiyapāḷi", "Mūla > Vinayapiṭaka > Pācittiyapāḷi [vin02m1.mul.html.txt]"],
    "vin02m2.mul.html.txt": ["3", "Mūla > Vinayapiṭaka > Mahāvaggapāḷi", "Mūla > Vinayapiṭaka > Mahāvaggapāḷi [vin02m2.mul.html.txt]"],
    "vin02m3.mul.html.txt": ["4", "Mūla > Vinayapiṭaka > Cūḷavaggapāḷi", "Mūla > Vinayapiṭaka > Cūḷavaggapāḷi [vin02m3.mul.html.txt]"],
    "vin02m4.mul.html.txt": ["5", "Mūla > Vinayapiṭaka > Parivārapāḷi", "Mūla > Vinayapiṭaka > Parivārapāḷi [vin02m4.mul.html.txt]"],
    "s0101m.mul.html.txt": ["6", "Mūla > Dīghanikāya > Sīlakkhandhavaggapāḷi", "Mūla > Dīghanikāya > Sīlakkhandhavaggapāḷi [s0101m.mul.html.txt]"],
    "s0102m.mul.html.txt": ["7", "Mūla > Dīghanikāya > Mahāvaggapāḷi", "Mūla > Dīghanikāya > Mahāvaggapāḷi [s0102m.mul.html.txt]"],
    "s0103m.mul.html.txt": ["8", "Mūla > Dīghanikāya > Pāthikavaggapāḷi", "Mūla > Dīghanikāya > Pāthikavaggapāḷi [s0103m.mul.html.txt]"],
    "s0201m.mul.html.txt": ["9", "Mūla > Majjhimanikāya > Mūlapaṇṇāsapāḷi", "Mūla > Majjhimanikāya > Mūlapaṇṇāsapāḷi [s0201m.mul.html.txt]"],
    "s0202m.mul.html.txt": ["10", "Mūla > Majjhimanikāya > Majjhimapaṇṇāsapāḷi", "Mūla > Majjhimanikāya > Majjhimapaṇṇāsapāḷi [s0202m.mul.html.txt]"],
    "s0203m.mul.html.txt": ["11", "Mūla > Majjhimanikāya > Uparipaṇṇāsapāḷi", "Mūla > Majjhimanikāya > Uparipaṇṇāsapāḷi [s0203m.mul.html.txt]"],
    "s0301m.mul.html.txt": ["12", "Mūla > Saṃyuttanikāya > Sagāthāvaggapāḷi", "Mūla > Saṃyuttanikāya > Sagāthāvaggapāḷi [s0301m.mul.html.txt]"],
    "s0302m.mul.html.txt": ["13", "Mūla > Saṃyuttanikāya > Nidānavaggapāḷi", "Mūla > Saṃyuttanikāya > Nidānavaggapāḷi [s0302m.mul.html.txt]"],
    "s0303m.mul.html.txt": ["14", "Mūla > Saṃyuttanikāya > Khandhavaggapāḷi", "Mūla > Saṃyuttanikāya > Khandhavaggapāḷi [s0303m.mul.html.txt]"],
    "s0304m.mul.html.txt": ["15", "Mūla > Saṃyuttanikāya > Saḷāyatanavaggapāḷi", "Mūla > Saṃyuttanikāya > Saḷāyatanavaggapāḷi [s0304m.mul.html.txt]"],
    "s0305m.mul.html.txt": ["16", "Mūla > Saṃyuttanikāya > Mahāvaggapāḷi", "Mūla > Saṃyuttanikāya > Mahāvaggapāḷi [s0305m.mul.html.txt]"],
    "s0401m.mul.html.txt": ["17", "Mūla > Aṅguttaranikāya > Ekakanipātapāḷi", "Mūla > Aṅguttaranikāya > Ekakanipātapāḷi [s0401m.mul.html.txt]"],
    "s0402m1.mul.html.txt": ["18", "Mūla > Aṅguttaranikāya > Dukanipātapāḷi", "Mūla > Aṅguttaranikāya > Dukanipātapāḷi [s0402m1.mul.html.txt]"],
    "s0402m2.mul.html.txt": ["19", "Mūla > Aṅguttaranikāya > Tikanipātapāḷi", "Mūla > Aṅguttaranikāya > Tikanipātapāḷi [s0402m2.mul.html.txt]"],
    "s0402m3.mul.html.txt": ["20", "Mūla > Aṅguttaranikāya > Catukkanipātapāḷi", "Mūla > Aṅguttaranikāya > Catukkanipātapāḷi [s0402m3.mul.html.txt]"],
    "s0403m1.mul.html.txt": ["21", "Mūla > Aṅguttaranikāya > Pañcakanipātapāḷi", "Mūla > Aṅguttaranikāya > Pañcakanipātapāḷi [s0403m1.mul.html.txt]"],
    "s0403m2.mul.html.txt": ["22", "Mūla > Aṅguttaranikāya > Chakkanipātapāḷi", "Mūla > Aṅguttaranikāya > Chakkanipātapāḷi [s0403m2.mul.html.txt]"],
    "s0403m3.mul.html.txt": ["23", "Mūla > Aṅguttaranikāya > Sattakanipātapāḷi", "Mūla > Aṅguttaranikāya > Sattakanipātapāḷi [s0403m3.mul.html.txt]"],
    "s0404m1.mul.html.txt": ["24", "Mūla > Aṅguttaranikāya > Aṭṭhakādinipātapāḷi", "Mūla > Aṅguttaranikāya > Aṭṭhakādinipātapāḷi [s0404m1.mul.html.txt]"],
    "s0404m2.mul.html.txt": ["25", "Mūla > Aṅguttaranikāya > Navakanipātapāḷi", "Mūla > Aṅguttaranikāya > Navakanipātapāḷi [s0404m2.mul.html.txt]"],
    "s0404m3.mul.html.txt": ["26", "Mūla > Aṅguttaranikāya > Dasakanipātapāḷi", "Mūla > Aṅguttaranikāya > Dasakanipātapāḷi [s0404m3.mul.html.txt]"],
    "s0404m4.mul.html.txt": ["27", "Mūla > Aṅguttaranikāya > Ekādasakanipātapāḷi", "Mūla > Aṅguttaranikāya > Ekādasakanipātapāḷi [s0404m4.mul.html.txt]"],
    "s0501m.mul.html.txt": ["28", "Mūla > Khuddakanikāya > Khuddakapāṭhapāḷi", "Mūla > Khuddakanikāya > Khuddakapāṭhapāḷi [s0501m.mul.html.txt]"],
    "s0502m.mul.html.txt": ["29", "Mūla > Khuddakanikāya > Dhammapadapāḷi", "Mūla > Khuddakanikāya > Dhammapadapāḷi [s0502m.mul.html.txt]"],
    "s0503m.mul.html.txt": ["30", "Mūla > Khuddakanikāya > Udānapāḷi", "Mūla > Khuddakanikāya > Udānapāḷi [s0503m.mul.html.txt]"],
    "s0504m.mul.html.txt": ["31", "Mūla > Khuddakanikāya > Itivuttakapāḷi", "Mūla > Khuddakanikāya > Itivuttakapāḷi [s0504m.mul.html.txt]"],
    "s0505m.mul.html.txt": ["32", "Mūla > Khuddakanikāya > Suttanipātapāḷi", "Mūla > Khuddakanikāya > Suttanipātapāḷi [s0505m.mul.html.txt]"],
    "s0506m.mul.html.txt": ["33", "Mūla > Khuddakanikāya > Vimānavatthupāḷi", "Mūla > Khuddakanikāya > Vimānavatthupāḷi [s0506m.mul.html.txt]"],
    "s0507m.mul.html.txt": ["34", "Mūla > Khuddakanikāya > Petavatthupāḷi", "Mūla > Khuddakanikāya > Petavatthupāḷi [s0507m.mul.html.txt]"],
    "s0508m.mul.html.txt": ["35", "Mūla > Khuddakanikāya > Theragāthāpāḷi", "Mūla > Khuddakanikāya > Theragāthāpāḷi [s0508m.mul.html.txt]"],
    "s0509m.mul.html.txt": ["36", "Mūla > Khuddakanikāya > Therīgāthāpāḷi", "Mūla > Khuddakanikāya > Therīgāthāpāḷi [s0509m.mul.html.txt]"],
    "s0510m1.mul.html.txt": ["37", "Mūla > Khuddakanikāya > Apadānapāḷi-1", "Mūla > Khuddakanikāya > Apadānapāḷi-1 [s0510m1.mul.html.txt]"],
    "s0510m2.mul.html.txt": ["38", "Mūla > Khuddakanikāya > Apadānapāḷi-2", "Mūla > Khuddakanikāya > Apadānapāḷi-2 [s0510m2.mul.html.txt]"],
    "s0511m.mul.html.txt": ["39", "Mūla > Khuddakanikāya > Buddhavaṃsapāḷi", "Mūla > Khuddakanikāya > Buddhavaṃsapāḷi [s0511m.mul.html.txt]"],
    "s0512m.mul.html.txt": ["40", "Mūla > Khuddakanikāya > Cariyāpiṭakapāḷi", "Mūla > Khuddakanikāya > Cariyāpiṭakapāḷi [s0512m.mul.html.txt]"],
    "s0513m.mul.html.txt": ["41", "Mūla > Khuddakanikāya > Jātakapāḷi-1", "Mūla > Khuddakanikāya > Jātakapāḷi-1 [s0513m.mul.html.txt]"],
    "s0514m.mul.html.txt": ["42", "Mūla > Khuddakanikāya > Jātakapāḷi-2", "Mūla > Khuddakanikāya > Jātakapāḷi-2 [s0514m.mul.html.txt]"],
    "s0515m.mul.html.txt": ["43", "Mūla > Khuddakanikāya > Mahāniddesapāḷi", "Mūla > Khuddakanikāya > Mahāniddesapāḷi [s0515m.mul.html.txt]"],
    "s0516m.mul.html.txt": ["44", "Mūla > Khuddakanikāya > Cūḷaniddesapāḷi", "Mūla > Khuddakanikāya > Cūḷaniddesapāḷi [s0516m.mul.html.txt]"],
    "s0517m.mul.html.txt": ["45", "Mūla > Khuddakanikāya > Paṭisambhidāmaggapāḷi", "Mūla > Khuddakanikāya > Paṭisambhidāmaggapāḷi [s0517m.mul.html.txt]"],
    "s0519m.mul.html.txt": ["46", "Mūla > Khuddakanikāya > Nettippakaraṇapāḷi", "Mūla > Khuddakanikāya > Nettippakaraṇapāḷi [s0519m.mul.html.txt]"],
    "s0518m.nrf.html.txt": ["47", "Mūla > Khuddakanikāya > Milindapañhapāḷi", "Mūla > Khuddakanikāya > Milindapañhapāḷi [s0518m.nrf.html.txt]"],
    "s0520m.nrf.html.txt": ["48", "Mūla > Khuddakanikāya > Peṭakopadesapāḷi", "Mūla > Khuddakanikāya > Peṭakopadesapāḷi [s0520m.nrf.html.txt]"],
    "abh01m.mul.html.txt": ["49", "Mūla > Abhidhammapiṭaka > Dhammasaṅgaṇīpāḷi", "Mūla > Abhidhammapiṭaka > Dhammasaṅgaṇīpāḷi [abh01m.mul.html.txt]"],
    "abh02m.mul.html.txt": ["50", "Mūla > Abhidhammapiṭaka > Vibhaṅgapāḷi", "Mūla > Abhidhammapiṭaka > Vibhaṅgapāḷi [abh02m.mul.html.txt]"],
    "abh03m1.mul.html.txt": ["51", "Mūla > Abhidhammapiṭaka > Dhātukathāpāḷi", "Mūla > Abhidhammapiṭaka > Dhātukathāpāḷi [abh03m1.mul.html.txt]"],
    "abh03m2.mul.html.txt": ["52", "Mūla > Abhidhammapiṭaka > Puggalapaññattipāḷi", "Mūla > Abhidhammapiṭaka > Puggalapaññattipāḷi [abh03m2.mul.html.txt]"],
    "abh03m3.mul.html.txt": ["53", "Mūla > Abhidhammapiṭaka > Kathāvatthupāḷi", "Mūla > Abhidhammapiṭaka > Kathāvatthupāḷi [abh03m3.mul.html.txt]"],
    "abh03m4.mul.html.txt": ["54", "Mūla > Abhidhammapiṭaka > Yamakapāḷi-1", "Mūla > Abhidhammapiṭaka > Yamakapāḷi-1 [abh03m4.mul.html.txt]"],
    "abh03m5.mul.html.txt": ["55", "Mūla > Abhidhammapiṭaka > Yamakapāḷi-2", "Mūla > Abhidhammapiṭaka > Yamakapāḷi-2 [abh03m5.mul.html.txt]"],
    "abh03m6.mul.html.txt": ["56", "Mūla > Abhidhammapiṭaka > Yamakapāḷi-3", "Mūla > Abhidhammapiṭaka > Yamakapāḷi-3 [abh03m6.mul.html.txt]"],
    "abh03m7.mul.html.txt": ["57", "Mūla > Abhidhammapiṭaka > Paṭṭhānapāḷi-1", "Mūla > Abhidhammapiṭaka > Paṭṭhānapāḷi-1 [abh03m7.mul.html.txt]"],
    "abh03m8.mul.html.txt": ["58", "Mūla > Abhidhammapiṭaka > Paṭṭhānapāḷi-2", "Mūla > Abhidhammapiṭaka > Paṭṭhānapāḷi-2 [abh03m8.mul.html.txt]"],
    "abh03m9.mul.html.txt": ["59", "Mūla > Abhidhammapiṭaka > Paṭṭhānapāḷi-3", "Mūla > Abhidhammapiṭaka > Paṭṭhānapāḷi-3 [abh03m9.mul.html.txt]"],
    "abh03m10.mul.html.txt": ["60", "Mūla > Abhidhammapiṭaka > Paṭṭhānapāḷi-4", "Mūla > Abhidhammapiṭaka > Paṭṭhānapāḷi-4 [abh03m10.mul.html.txt]"],
    "abh03m11.mul.html.txt": ["61", "Mūla > Abhidhammapiṭaka > Paṭṭhānapāḷi-5", "Mūla > Abhidhammapiṭaka > Paṭṭhānapāḷi-5 [abh03m11.mul.html.txt]"],
    "vin01a.att.html.txt": ["62", "Aṭṭhakathā > Vinayapiṭaka (aṭṭhakathā) > Pārājikakaṇḍa-aṭṭhakathā", "Aṭṭhakathā > Vinayapiṭaka (aṭṭhakathā) > Pārājikakaṇḍa-aṭṭhakathā [vin01a.att.html.txt]"],
    "vin02a1.att.html.txt": ["63", "Aṭṭhakathā > Vinayapiṭaka (aṭṭhakathā) > Pācittiya-aṭṭhakathā", "Aṭṭhakathā > Vinayapiṭaka (aṭṭhakathā) > Pācittiya-aṭṭhakathā [vin02a1.att.html.txt]"],
    "vin02a2.att.html.txt": ["64", "Aṭṭhakathā > Vinayapiṭaka (aṭṭhakathā) > Mahāvagga-aṭṭhakathā", "Aṭṭhakathā > Vinayapiṭaka (aṭṭhakathā) > Mahāvagga-aṭṭhakathā [vin02a2.att.html.txt]"],
    "vin02a3.att.html.txt": ["65", "Aṭṭhakathā > Vinayapiṭaka (aṭṭhakathā) > Cūḷavagga-aṭṭhakathā", "Aṭṭhakathā > Vinayapiṭaka (aṭṭhakathā) > Cūḷavagga-aṭṭhakathā [vin02a3.att.html.txt]"],
    "vin02a4.att.html.txt": ["66", "Aṭṭhakathā > Vinayapiṭaka (aṭṭhakathā) > Parivāra-aṭṭhakathā", "Aṭṭhakathā > Vinayapiṭaka (aṭṭhakathā) > Parivāra-aṭṭhakathā [vin02a4.att.html.txt]"],
    "s0101a.att.html.txt": ["67", "Aṭṭhakathā > Dīgha nikāya (aṭṭhakathā) > Sīlakkhandhavagga-aṭṭhakathā", "Aṭṭhakathā > Dīgha nikāya (aṭṭhakathā) > Sīlakkhandhavagga-aṭṭhakathā [s0101a.att.html.txt]"],
    "s0102a.att.html.txt": ["68", "Aṭṭhakathā > Dīgha nikāya (aṭṭhakathā) > Mahāvagga-aṭṭhakathā", "Aṭṭhakathā > Dīgha nikāya (aṭṭhakathā) > Mahāvagga-aṭṭhakathā [s0102a.att.html.txt]"],
    "s0103a.att.html.txt": ["69", "Aṭṭhakathā > Dīgha nikāya (aṭṭhakathā) > Pāthikavagga-aṭṭhakathā", "Aṭṭhakathā > Dīgha nikāya (aṭṭhakathā) > Pāthikavagga-aṭṭhakathā [s0103a.att.html.txt]"],
    "s0201a.att.html.txt": ["70", "Aṭṭhakathā > Majjhimanikāya (aṭṭhakathā) > Mūlapaṇṇāsa-aṭṭhakathā", "Aṭṭhakathā > Majjhimanikāya (aṭṭhakathā) > Mūlapaṇṇāsa-aṭṭhakathā [s0201a.att.html.txt]"],
    "s0202a.att.html.txt": ["71", "Aṭṭhakathā > Majjhimanikāya (aṭṭhakathā) > Majjhimapaṇṇāsa-aṭṭhakathā", "Aṭṭhakathā > Majjhimanikāya (aṭṭhakathā) > Majjhimapaṇṇāsa-aṭṭhakathā [s0202a.att.html.txt]"],
    "s0203a.att.html.txt": ["72", "Aṭṭhakathā > Majjhimanikāya (aṭṭhakathā) > Uparipaṇṇāsa-aṭṭhakathā", "Aṭṭhakathā > Majjhimanikāya (aṭṭhakathā) > Uparipaṇṇāsa-aṭṭhakathā [s0203a.att.html.txt]"],
    "s0301a.att.html.txt": ["73", "Aṭṭhakathā > Saṃyuttanikāya (aṭṭhakathā) > Sagāthāvagga-aṭṭhakathā", "Aṭṭhakathā > Saṃyuttanikāya (aṭṭhakathā) > Sagāthāvagga-aṭṭhakathā [s0301a.att.html.txt]"],
    "s0302a.att.html.txt": ["74", "Aṭṭhakathā > Saṃyuttanikāya (aṭṭhakathā) > Nidānavagga-aṭṭhakathā", "Aṭṭhakathā > Saṃyuttanikāya (aṭṭhakathā) > Nidānavagga-aṭṭhakathā [s0302a.att.html.txt]"],
    "s0303a.att.html.txt": ["75", "Aṭṭhakathā > Saṃyuttanikāya (aṭṭhakathā) > Khandhavagga-aṭṭhakathā", "Aṭṭhakathā > Saṃyuttanikāya (aṭṭhakathā) > Khandhavagga-aṭṭhakathā [s0303a.att.html.txt]"],
    "s0304a.att.html.txt": ["76", "Aṭṭhakathā > Saṃyuttanikāya (aṭṭhakathā) > Saḷāyatanavagga-aṭṭhakathā", "Aṭṭhakathā > Saṃyuttanikāya (aṭṭhakathā) > Saḷāyatanavagga-aṭṭhakathā [s0304a.att.html.txt]"],
    "s0305a.att.html.txt": ["77", "Aṭṭhakathā > Saṃyuttanikāya (aṭṭhakathā) > Mahāvagga-aṭṭhakathā", "Aṭṭhakathā > Saṃyuttanikāya (aṭṭhakathā) > Mahāvagga-aṭṭhakathā [s0305a.att.html.txt]"],
    "s0401a.att.html.txt": ["78", "Aṭṭhakathā > Aṅguttaranikāya (aṭṭhakathā) > Ekakanipāta-aṭṭhakathā", "Aṭṭhakathā > Aṅguttaranikāya (aṭṭhakathā) > Ekakanipāta-aṭṭhakathā [s0401a.att.html.txt]"],
    "s0402a.att.html.txt": ["79", "Aṭṭhakathā > Aṅguttaranikāya (aṭṭhakathā) > Duka-tika-catukkanipāta-aṭṭhakathā", "Aṭṭhakathā > Aṅguttaranikāya (aṭṭhakathā) > Duka-tika-catukkanipāta-aṭṭhakathā [s0402a.att.html.txt]"],
    "s0403a.att.html.txt": ["80", "Aṭṭhakathā > Aṅguttaranikāya (aṭṭhakathā) > Pañcaka-chakka-sattakanipāta-aṭṭhakathā", "Aṭṭhakathā > Aṅguttaranikāya (aṭṭhakathā) > Pañcaka-chakka-sattakanipāta-aṭṭhakathā [s0403a.att.html.txt]"],
    "s0404a.att.html.txt": ["81", "Aṭṭhakathā > Aṅguttaranikāya (aṭṭhakathā) > Aṭṭhakādinipāta-aṭṭhakathā", "Aṭṭhakathā > Aṅguttaranikāya (aṭṭhakathā) > Aṭṭhakādinipāta-aṭṭhakathā [s0404a.att.html.txt]"],
    "s0501a.att.html.txt": ["82", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Khuddakapāṭha-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Khuddakapāṭha-aṭṭhakathā [s0501a.att.html.txt]"],
    "s0502a.att.html.txt": ["83", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Dhammapada-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Dhammapada-aṭṭhakathā [s0502a.att.html.txt]"],
    "s0503a.att.html.txt": ["84", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Udāna-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Udāna-aṭṭhakathā [s0503a.att.html.txt]"],
    "s0504a.att.html.txt": ["85", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Itivuttaka-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Itivuttaka-aṭṭhakathā [s0504a.att.html.txt]"],
    "s0505a.att.html.txt": ["86", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Suttanipāta-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Suttanipāta-aṭṭhakathā [s0505a.att.html.txt]"],
    "s0506a.att.html.txt": ["87", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Vimānavatthu-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Vimānavatthu-aṭṭhakathā [s0506a.att.html.txt]"],
    "s0507a.att.html.txt": ["88", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Petavatthu-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Petavatthu-aṭṭhakathā [s0507a.att.html.txt]"],
    "s0508a1.att.html.txt": ["89", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Theragāthā-aṭṭhakathā-1", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Theragāthā-aṭṭhakathā-1 [s0508a1.att.html.txt]"],
    "s0508a2.att.html.txt": ["90", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Theragāthā-aṭṭhakathā-2", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Theragāthā-aṭṭhakathā-2 [s0508a2.att.html.txt]"],
    "s0509a.att.html.txt": ["91", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Therīgāthā-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Therīgāthā-aṭṭhakathā [s0509a.att.html.txt]"],
    "s0510a.att.html.txt": ["92", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Apadāna-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Apadāna-aṭṭhakathā [s0510a.att.html.txt]"],
    "s0511a.att.html.txt": ["93", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Buddhavaṃsa-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Buddhavaṃsa-aṭṭhakathā [s0511a.att.html.txt]"],
    "s0512a.att.html.txt": ["94", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Cariyāpiṭaka-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Cariyāpiṭaka-aṭṭhakathā [s0512a.att.html.txt]"],
    "s0513a1.att.html.txt": ["95", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-1", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-1 [s0513a1.att.html.txt]"],
    "s0513a2.att.html.txt": ["96", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-2", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-2 [s0513a2.att.html.txt]"],
    "s0513a3.att.html.txt": ["97", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-3", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-3 [s0513a3.att.html.txt]"],
    "s0513a4.att.html.txt": ["98", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-4", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-4 [s0513a4.att.html.txt]"],
    "s0514a1.att.html.txt": ["99", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-5", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-5 [s0514a1.att.html.txt]"],
    "s0514a2.att.html.txt": ["100", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-6", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-6 [s0514a2.att.html.txt]"],
    "s0514a3.att.html.txt": ["101", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-7", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Jātaka-aṭṭhakathā-7 [s0514a3.att.html.txt]"],
    "s0515a.att.html.txt": ["102", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Mahāniddesa-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Mahāniddesa-aṭṭhakathā [s0515a.att.html.txt]"],
    "s0516a.att.html.txt": ["103", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Cūḷaniddesa-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Cūḷaniddesa-aṭṭhakathā [s0516a.att.html.txt]"],
    "s0517a.att.html.txt": ["104", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Paṭisambhidāmagga-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Paṭisambhidāmagga-aṭṭhakathā [s0517a.att.html.txt]"],
    "s0519a.att.html.txt": ["105", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Nettippakaraṇa-aṭṭhakathā", "Aṭṭhakathā > Khuddakanikāya (aṭṭhakathā) > Nettippakaraṇa-aṭṭhakathā [s0519a.att.html.txt]"],
    "abh01a.att.html.txt": ["106", "Aṭṭhakathā > Abhidhammapiṭaka (aṭṭhakathā) > Dhammasaṅgaṇi-aṭṭhakathā", "Aṭṭhakathā > Abhidhammapiṭaka (aṭṭhakathā) > Dhammasaṅgaṇi-aṭṭhakathā [abh01a.att.html.txt]"],
    "abh02a.att.html.txt": ["107", "Aṭṭhakathā > Abhidhammapiṭaka (aṭṭhakathā) > Sammohavinodanī-aṭṭhakathā", "Aṭṭhakathā > Abhidhammapiṭaka (aṭṭhakathā) > Sammohavinodanī-aṭṭhakathā [abh02a.att.html.txt]"],
    "abh03a.att.html.txt": ["108", "Aṭṭhakathā > Abhidhammapiṭaka (aṭṭhakathā) > Pañcapakaraṇa-aṭṭhakathā", "Aṭṭhakathā > Abhidhammapiṭaka (aṭṭhakathā) > Pañcapakaraṇa-aṭṭhakathā [abh03a.att.html.txt]"],
    "vin01t1.tik.html.txt": ["109", "Tīkā > Vinayapiṭaka (ṭīkā) > Sāratthadīpanī-ṭīkā-1", "Tīkā > Vinayapiṭaka (ṭīkā) > Sāratthadīpanī-ṭīkā-1 [vin01t1.tik.html.txt]"],
    "vin01t2.tik.html.txt": ["110", "Tīkā > Vinayapiṭaka (ṭīkā) > Sāratthadīpanī-ṭīkā-2", "Tīkā > Vinayapiṭaka (ṭīkā) > Sāratthadīpanī-ṭīkā-2 [vin01t2.tik.html.txt]"],
    "vin02t.tik.html.txt": ["111", "Tīkā > Vinayapiṭaka (ṭīkā) > Sāratthadīpanī-ṭīkā-3", "Tīkā > Vinayapiṭaka (ṭīkā) > Sāratthadīpanī-ṭīkā-3 [vin02t.tik.html.txt]"],
    "vin04t.nrf.html.txt": ["112", "Tīkā > Vinayapiṭaka (ṭīkā) > Dvemātikāpāḷi", "Tīkā > Vinayapiṭaka (ṭīkā) > Dvemātikāpāḷi [vin04t.nrf.html.txt]"],
    "vin05t.nrf.html.txt": ["113", "Tīkā > Vinayapiṭaka (ṭīkā) > Vinayasaṅgaha-aṭṭhakathā", "Tīkā > Vinayapiṭaka (ṭīkā) > Vinayasaṅgaha-aṭṭhakathā [vin05t.nrf.html.txt]"],
    "vin06t.nrf.html.txt": ["114", "Tīkā > Vinayapiṭaka (ṭīkā) > Vajirabuddhi-ṭīkā", "Tīkā > Vinayapiṭaka (ṭīkā) > Vajirabuddhi-ṭīkā [vin06t.nrf.html.txt]"],
    "vin07t.nrf.html.txt": ["115", "Tīkā > Vinayapiṭaka (ṭīkā) > Vimativinodanī-ṭīkā", "Tīkā > Vinayapiṭaka (ṭīkā) > Vimativinodanī-ṭīkā [vin07t.nrf.html.txt]"],
    "vin08t.nrf.html.txt": ["116", "Tīkā > Vinayapiṭaka (ṭīkā) > Vinayālaṅkāra-ṭīkā", "Tīkā > Vinayapiṭaka (ṭīkā) > Vinayālaṅkāra-ṭīkā [vin08t.nrf.html.txt]"],
    "vin09t.nrf.html.txt": ["117", "Tīkā > Vinayapiṭaka (ṭīkā) > Kaṅkhāvitaraṇīpurāṇa-ṭīkā", "Tīkā > Vinayapiṭaka (ṭīkā) > Kaṅkhāvitaraṇīpurāṇa-ṭīkā [vin09t.nrf.html.txt]"],
    "vin10t.nrf.html.txt": ["118", "Tīkā > Vinayapiṭaka (ṭīkā) > Vinayavinicchaya-uttaravinicchaya", "Tīkā > Vinayapiṭaka (ṭīkā) > Vinayavinicchaya-uttaravinicchaya [vin10t.nrf.html.txt]"],
    "vin11t.nrf.html.txt": ["119", "Tīkā > Vinayapiṭaka (ṭīkā) > Vinayavinicchaya-ṭīkā", "Tīkā > Vinayapiṭaka (ṭīkā) > Vinayavinicchaya-ṭīkā [vin11t.nrf.html.txt]"],
    "vin12t.nrf.html.txt": ["120", "Tīkā > Vinayapiṭaka (ṭīkā) > Pācityādiyojanāpāḷi", "Tīkā > Vinayapiṭaka (ṭīkā) > Pācityādiyojanāpāḷi [vin12t.nrf.html.txt]"],
    "vin13t.nrf.html.txt": ["121", "Tīkā > Vinayapiṭaka (ṭīkā) > Khuddasikkhā-mūlasikkhā", "Tīkā > Vinayapiṭaka (ṭīkā) > Khuddasikkhā-mūlasikkhā [vin13t.nrf.html.txt]"],
    "s0101t.tik.html.txt": ["122", "Tīkā > Dīghanikāya (ṭīkā) > Sīlakkhandhavagga-ṭīkā", "Tīkā > Dīghanikāya (ṭīkā) > Sīlakkhandhavagga-ṭīkā [s0101t.tik.html.txt]"],
    "s0102t.tik.html.txt": ["123", "Tīkā > Dīghanikāya (ṭīkā) > Mahāvagga-ṭīkā", "Tīkā > Dīghanikāya (ṭīkā) > Mahāvagga-ṭīkā [s0102t.tik.html.txt]"],
    "s0103t.tik.html.txt": ["124", "Tīkā > Dīghanikāya (ṭīkā) > Pāthikavagga-ṭīkā", "Tīkā > Dīghanikāya (ṭīkā) > Pāthikavagga-ṭīkā [s0103t.tik.html.txt]"],
    "s0104t.nrf.html.txt": ["125", "Tīkā > Dīghanikāya (ṭīkā) > Sīlakkhandhavagga-abhinavaṭīkā-1", "Tīkā > Dīghanikāya (ṭīkā) > Sīlakkhandhavagga-abhinavaṭīkā-1 [s0104t.nrf.html.txt]"],
    "s0105t.nrf.html.txt": ["126", "Tīkā > Dīghanikāya (ṭīkā) > Sīlakkhandhavagga-abhinavaṭīkā-2", "Tīkā > Dīghanikāya (ṭīkā) > Sīlakkhandhavagga-abhinavaṭīkā-2 [s0105t.nrf.html.txt]"],
    "s0201t.tik.html.txt": ["127", "Tīkā > Majjhimanikāya (ṭīkā) > Mūlapaṇṇāsa-ṭīkā", "Tīkā > Majjhimanikāya (ṭīkā) > Mūlapaṇṇāsa-ṭīkā [s0201t.tik.html.txt]"],
    "s0202t.tik.html.txt": ["128", "Tīkā > Majjhimanikāya (ṭīkā) > Majjhimapaṇṇāsa-ṭīkā", "Tīkā > Majjhimanikāya (ṭīkā) > Majjhimapaṇṇāsa-ṭīkā [s0202t.tik.html.txt]"],
    "s0203t.tik.html.txt": ["129", "Tīkā > Majjhimanikāya (ṭīkā) > Uparipaṇṇāsa-ṭīkā", "Tīkā > Majjhimanikāya (ṭīkā) > Uparipaṇṇāsa-ṭīkā [s0203t.tik.html.txt]"],
    "s0301t.tik.html.txt": ["130", "Tīkā > Saṃyuttanikāya (ṭīkā) > Sagāthāvagga-ṭīkā", "Tīkā > Saṃyuttanikāya (ṭīkā) > Sagāthāvagga-ṭīkā [s0301t.tik.html.txt]"],
    "s0302t.tik.html.txt": ["131", "Tīkā > Saṃyuttanikāya (ṭīkā) > Nidānavagga-ṭīkā", "Tīkā > Saṃyuttanikāya (ṭīkā) > Nidānavagga-ṭīkā [s0302t.tik.html.txt]"],
    "s0303t.tik.html.txt": ["132", "Tīkā > Saṃyuttanikāya (ṭīkā) > Khandhavagga-ṭīkā", "Tīkā > Saṃyuttanikāya (ṭīkā) > Khandhavagga-ṭīkā [s0303t.tik.html.txt]"],
    "s0304t.tik.html.txt": ["133", "Tīkā > Saṃyuttanikāya (ṭīkā) > Saḷāyatanavagga-ṭīkā", "Tīkā > Saṃyuttanikāya (ṭīkā) > Saḷāyatanavagga-ṭīkā [s0304t.tik.html.txt]"],
    "s0305t.tik.html.txt": ["134", "Tīkā > Saṃyuttanikāya (ṭīkā) > Mahāvagga-ṭīkā", "Tīkā > Saṃyuttanikāya (ṭīkā) > Mahāvagga-ṭīkā [s0305t.tik.html.txt]"],
    "s0401t.tik.html.txt": ["135", "Tīkā > Aṅguttaranikāya (ṭīkā) > Ekakanipāta-ṭīkā", "Tīkā > Aṅguttaranikāya (ṭīkā) > Ekakanipāta-ṭīkā [s0401t.tik.html.txt]"],
    "s0402t.tik.html.txt": ["136", "Tīkā > Aṅguttaranikāya (ṭīkā) > Duka-tika-catukkanipāta-ṭīkā", "Tīkā > Aṅguttaranikāya (ṭīkā) > Duka-tika-catukkanipāta-ṭīkā [s0402t.tik.html.txt]"],
    "s0403t.tik.html.txt": ["137", "Tīkā > Aṅguttaranikāya (ṭīkā) > Pañcaka-chakka-sattakanipāta-ṭīkā", "Tīkā > Aṅguttaranikāya (ṭīkā) > Pañcaka-chakka-sattakanipāta-ṭīkā [s0403t.tik.html.txt]"],
    "s0404t.tik.html.txt": ["138", "Tīkā > Aṅguttaranikāya (ṭīkā) > Aṭṭhakādinipāta-ṭīkā", "Tīkā > Aṅguttaranikāya (ṭīkā) > Aṭṭhakādinipāta-ṭīkā [s0404t.tik.html.txt]"],
    "s0519t.tik.html.txt": ["139", "Tīkā > Khuddakanikāya (ṭīkā) > Nettippakaraṇa-ṭīkā", "Tīkā > Khuddakanikāya (ṭīkā) > Nettippakaraṇa-ṭīkā [s0519t.tik.html.txt]"],
    "s0501t.nrf.html.txt": ["140", "Tīkā > Khuddakanikāya (ṭīkā) > Nettivibhāvinī", "Tīkā > Khuddakanikāya (ṭīkā) > Nettivibhāvinī [s0501t.nrf.html.txt]"],
    "abh01t.tik.html.txt": ["141", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Dhammasaṅgaṇī-mūlaṭīkā", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Dhammasaṅgaṇī-mūlaṭīkā [abh01t.tik.html.txt]"],
    "abh02t.tik.html.txt": ["142", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Vibhaṅga-mūlaṭīkā", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Vibhaṅga-mūlaṭīkā [abh02t.tik.html.txt]"],
    "abh03t.tik.html.txt": ["143", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Pañcapakaraṇa-mūlaṭīkā", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Pañcapakaraṇa-mūlaṭīkā [abh03t.tik.html.txt]"],
    "abh04t.nrf.html.txt": ["144", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Dhammasaṅgaṇī-anuṭīkā", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Dhammasaṅgaṇī-anuṭīkā [abh04t.nrf.html.txt]"],
    "abh05t.nrf.html.txt": ["145", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Pañcapakaraṇa-anuṭīkā", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Pañcapakaraṇa-anuṭīkā [abh05t.nrf.html.txt]"],
    "abh06t.nrf.html.txt": ["146", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Abhidhammāvatāro-nāmarūpaparicchedo", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Abhidhammāvatāro-nāmarūpaparicchedo [abh06t.nrf.html.txt]"],
    "abh07t.nrf.html.txt": ["147", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Abhidhammatthasaṅgaho", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Abhidhammatthasaṅgaho [abh07t.nrf.html.txt]"],
    "abh08t.nrf.html.txt": ["148", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Abhidhammāvatāra-purāṇaṭīkā", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Abhidhammāvatāra-purāṇaṭīkā [abh08t.nrf.html.txt]"],
    "abh09t.nrf.html.txt": ["149", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Abhidhammamātikāpāḷi", "Tīkā > Abhidhammapiṭaka (ṭīkā) > Abhidhammamātikāpāḷi [abh09t.nrf.html.txt]"],
    "e0101n.mul.html.txt": ["150", "Añña > Visuddhimagga > Visuddhimagga-1", "Añña > Visuddhimagga > Visuddhimagga-1 [e0101n.mul.html.txt]"],
    "e0102n.mul.html.txt": ["151", "Añña > Visuddhimagga > Visuddhimagga-2", "Añña > Visuddhimagga > Visuddhimagga-2 [e0102n.mul.html.txt]"],
    "e0103n.att.html.txt": ["152", "Añña > Visuddhimagga > Visuddhimagga-mahāṭīkā-1", "Añña > Visuddhimagga > Visuddhimagga-mahāṭīkā-1 [e0103n.att.html.txt]"],
    "e0104n.att.html.txt": ["153", "Añña > Visuddhimagga > Visuddhimagga-mahāṭīkā-2", "Añña > Visuddhimagga > Visuddhimagga-mahāṭīkā-2 [e0104n.att.html.txt]"],
    "e0105n.nrf.html.txt": ["154", "Añña > Visuddhimagga > Visuddhimagga nidānakathā", "Añña > Visuddhimagga > Visuddhimagga nidānakathā [e0105n.nrf.html.txt]"],
    "e0901n.nrf.html.txt": ["155", "Añña > Saṅgāyana-puccha vissajjanā > Dīghanikāya (pu-vi)", "Añña > Saṅgāyana-puccha vissajjanā > Dīghanikāya (pu-vi) [e0901n.nrf.html.txt]"],
    "e0902n.nrf.html.txt": ["156", "Añña > Saṅgāyana-puccha vissajjanā > Majjhimanikāya (pu-vi)", "Añña > Saṅgāyana-puccha vissajjanā > Majjhimanikāya (pu-vi) [e0902n.nrf.html.txt]"],
    "e0903n.nrf.html.txt": ["157", "Añña > Saṅgāyana-puccha vissajjanā > Saṃyuttanikāya (pu-vi)", "Añña > Saṅgāyana-puccha vissajjanā > Saṃyuttanikāya (pu-vi) [e0903n.nrf.html.txt]"],
    "e0904n.nrf.html.txt": ["158", "Añña > Saṅgāyana-puccha vissajjanā > Aṅguttaranikāya (pu-vi)", "Añña > Saṅgāyana-puccha vissajjanā > Aṅguttaranikāya (pu-vi) [e0904n.nrf.html.txt]"],
    "e0905n.nrf.html.txt": ["159", "Añña > Saṅgāyana-puccha vissajjanā > Vinayapiṭaka (pu-vi)", "Añña > Saṅgāyana-puccha vissajjanā > Vinayapiṭaka (pu-vi) [e0905n.nrf.html.txt]"],
    "e0906n.nrf.html.txt": ["160", "Añña > Saṅgāyana-puccha vissajjanā > Abhidhammapiṭaka (pu-vi)", "Añña > Saṅgāyana-puccha vissajjanā > Abhidhammapiṭaka (pu-vi) [e0906n.nrf.html.txt]"],
    "e0907n.nrf.html.txt": ["161", "Añña > Saṅgāyana-puccha vissajjanā > Aṭṭhakathā (pu-vi)", "Añña > Saṅgāyana-puccha vissajjanā > Aṭṭhakathā (pu-vi) [e0907n.nrf.html.txt]"],
    "e0201n.nrf.html.txt": ["162", "Añña > Leḍī sayāḍo gantha-saṅgaho > Niruttidīpanī", "Añña > Leḍī sayāḍo gantha-saṅgaho > Niruttidīpanī [e0201n.nrf.html.txt]"],
    "e0301n.nrf.html.txt": ["163", "Añña > Leḍī sayāḍo gantha-saṅgaho > Paramatthadīpanī Saṅgahamahāṭīkāpāṭha", "Añña > Leḍī sayāḍo gantha-saṅgaho > Paramatthadīpanī Saṅgahamahāṭīkāpāṭha [e0301n.nrf.html.txt]"],
    "e0401n.nrf.html.txt": ["164", "Añña > Leḍī sayāḍo gantha-saṅgaho > Anudīpanīpāṭha", "Añña > Leḍī sayāḍo gantha-saṅgaho > Anudīpanīpāṭha [e0401n.nrf.html.txt]"],
    "e0501n.nrf.html.txt": ["165", "Añña > Leḍī sayāḍo gantha-saṅgaho > Paṭṭhānuddesa dīpanīpāṭha", "Añña > Leḍī sayāḍo gantha-saṅgaho > Paṭṭhānuddesa dīpanīpāṭha [e0501n.nrf.html.txt]"],
    "e0601n.nrf.html.txt": ["166", "Añña > Buddha-vandanā gantha-saṅgaho > Namakkāraṭīkā", "Añña > Buddha-vandanā gantha-saṅgaho > Namakkāraṭīkā [e0601n.nrf.html.txt]"],
    "e0602n.nrf.html.txt": ["167", "Añña > Buddha-vandanā gantha-saṅgaho > Mahāpaṇāmapāṭha", "Añña > Buddha-vandanā gantha-saṅgaho > Mahāpaṇāmapāṭha [e0602n.nrf.html.txt]"],
    "e0603n.nrf.html.txt": ["168", "Añña > Buddha-vandanā gantha-saṅgaho > Lakkhaṇāto buddhathomanāgāthā", "Añña > Buddha-vandanā gantha-saṅgaho > Lakkhaṇāto buddhathomanāgāthā [e0603n.nrf.html.txt]"],
    "e0604n.nrf.html.txt": ["169", "Añña > Buddha-vandanā gantha-saṅgaho > Sutavandanā", "Añña > Buddha-vandanā gantha-saṅgaho > Sutavandanā [e0604n.nrf.html.txt]"],
    "e0606n.nrf.html.txt": ["170", "Añña > Buddha-vandanā gantha-saṅgaho > Kamalāñjali", "Añña > Buddha-vandanā gantha-saṅgaho > Kamalāñjali [e0606n.nrf.html.txt]"],
    "e0605n.nrf.html.txt": ["171", "Añña > Buddha-vandanā gantha-saṅgaho > Jinālaṅkāra", "Añña > Buddha-vandanā gantha-saṅgaho > Jinālaṅkāra [e0605n.nrf.html.txt]"],
    "e0607n.nrf.html.txt": ["172", "Añña > Buddha-vandanā gantha-saṅgaho > Pajjamadhu", "Añña > Buddha-vandanā gantha-saṅgaho > Pajjamadhu [e0607n.nrf.html.txt]"],
    "e0608n.nrf.html.txt": ["173", "Añña > Buddha-vandanā gantha-saṅgaho > Buddhaguṇagāthāvalī", "Añña > Buddha-vandanā gantha-saṅgaho > Buddhaguṇagāthāvalī [e0608n.nrf.html.txt]"],
    "e0701n.nrf.html.txt": ["174", "Añña > Vaṃsa-gantha-saṅgaho > Cūḷaganthavaṃsa", "Añña > Vaṃsa-gantha-saṅgaho > Cūḷaganthavaṃsa [e0701n.nrf.html.txt]"],
    "e0703n.nrf.html.txt": ["175", "Añña > Vaṃsa-gantha-saṅgaho > Mahāvaṃsa", "Añña > Vaṃsa-gantha-saṅgaho > Mahāvaṃsa [e0703n.nrf.html.txt]"],
    "e0702n.nrf.html.txt": ["176", "Añña > Vaṃsa-gantha-saṅgaho > Sāsanavaṃsa", "Añña > Vaṃsa-gantha-saṅgaho > Sāsanavaṃsa [e0702n.nrf.html.txt]"],
    "e0802n.nrf.html.txt": ["177", "Añña > Byākaraṇa gantha-saṅgaho > Kaccāyanabyākaraṇaṃ", "Añña > Byākaraṇa gantha-saṅgaho > Kaccāyanabyākaraṇaṃ [e0802n.nrf.html.txt]"],
    "e0801n.nrf.html.txt": ["178", "Añña > Byākaraṇa gantha-saṅgaho > Moggallānabyākaraṇaṃ", "Añña > Byākaraṇa gantha-saṅgaho > Moggallānabyākaraṇaṃ [e0801n.nrf.html.txt]"],
    "e0803n.nrf.html.txt": ["179", "Añña > Byākaraṇa gantha-saṅgaho > Saddanītippakaraṇaṃ (padamālā)", "Añña > Byākaraṇa gantha-saṅgaho > Saddanītippakaraṇaṃ (padamālā) [e0803n.nrf.html.txt]"],
    "e0804n.nrf.html.txt": ["180", "Añña > Byākaraṇa gantha-saṅgaho > Saddanītippakaraṇaṃ (dhātumālā)", "Añña > Byākaraṇa gantha-saṅgaho > Saddanītippakaraṇaṃ (dhātumālā) [e0804n.nrf.html.txt]"],
    "e0805n.nrf.html.txt": ["181", "Añña > Byākaraṇa gantha-saṅgaho > Padarūpasiddhi", "Añña > Byākaraṇa gantha-saṅgaho > Padarūpasiddhi [e0805n.nrf.html.txt]"],
    "e0806n.nrf.html.txt": ["182", "Añña > Byākaraṇa gantha-saṅgaho > Mogallānapañcikā", "Añña > Byākaraṇa gantha-saṅgaho > Mogallānapañcikā [e0806n.nrf.html.txt]"],
    "e0807n.nrf.html.txt": ["183", "Añña > Byākaraṇa gantha-saṅgaho > Payogasiddhipāṭha", "Añña > Byākaraṇa gantha-saṅgaho > Payogasiddhipāṭha [e0807n.nrf.html.txt]"],
    "e0808n.nrf.html.txt": ["184", "Añña > Byākaraṇa gantha-saṅgaho > Vuttodayapāṭha", "Añña > Byākaraṇa gantha-saṅgaho > Vuttodayapāṭha [e0808n.nrf.html.txt]"],
    "e0809n.nrf.html.txt": ["185", "Añña > Byākaraṇa gantha-saṅgaho > Abhidhānappadīpikāpāṭha", "Añña > Byākaraṇa gantha-saṅgaho > Abhidhānappadīpikāpāṭha [e0809n.nrf.html.txt]"],
    "e0810n.nrf.html.txt": ["186", "Añña > Byākaraṇa gantha-saṅgaho > Abhidhānappadīpikāṭīkā", "Añña > Byākaraṇa gantha-saṅgaho > Abhidhānappadīpikāṭīkā [e0810n.nrf.html.txt]"],
    "e0811n.nrf.html.txt": ["187", "Añña > Byākaraṇa gantha-saṅgaho > Subodhālaṅkārapāṭha", "Añña > Byākaraṇa gantha-saṅgaho > Subodhālaṅkārapāṭha [e0811n.nrf.html.txt]"],
    "e0812n.nrf.html.txt": ["188", "Añña > Byākaraṇa gantha-saṅgaho > Subodhālaṅkāraṭīkā", "Añña > Byākaraṇa gantha-saṅgaho > Subodhālaṅkāraṭīkā [e0812n.nrf.html.txt]"],
    "e0813n.nrf.html.txt": ["189", "Añña > Byākaraṇa gantha-saṅgaho > Bālāvatāra gaṇṭhipadatthavinicchayasāra", "Añña > Byākaraṇa gantha-saṅgaho > Bālāvatāra gaṇṭhipadatthavinicchayasāra [e0813n.nrf.html.txt]"],
    "e1005n.nrf.html.txt": ["190", "Añña > Nīti-gantha-saṅgaho > Lokanīti", "Añña > Nīti-gantha-saṅgaho > Lokanīti [e1005n.nrf.html.txt]"],
    "e1006n.nrf.html.txt": ["191", "Añña > Nīti-gantha-saṅgaho > Suttantanīti", "Añña > Nīti-gantha-saṅgaho > Suttantanīti [e1006n.nrf.html.txt]"],
    "e1007n.nrf.html.txt": ["192", "Añña > Nīti-gantha-saṅgaho > Sūrassatinīti", "Añña > Nīti-gantha-saṅgaho > Sūrassatinīti [e1007n.nrf.html.txt]"],
    "e1004n.nrf.html.txt": ["193", "Añña > Nīti-gantha-saṅgaho > Mahārahanīti", "Añña > Nīti-gantha-saṅgaho > Mahārahanīti [e1004n.nrf.html.txt]"],
    "e1003n.nrf.html.txt": ["194", "Añña > Nīti-gantha-saṅgaho > Dhammanīti", "Añña > Nīti-gantha-saṅgaho > Dhammanīti [e1003n.nrf.html.txt]"],
    "e1001n.nrf.html.txt": ["195", "Añña > Nīti-gantha-saṅgaho > Kavidappaṇanīti", "Añña > Nīti-gantha-saṅgaho > Kavidappaṇanīti [e1001n.nrf.html.txt]"],
    "e1002n.nrf.html.txt": ["196", "Añña > Nīti-gantha-saṅgaho > Nītimañjarī", "Añña > Nīti-gantha-saṅgaho > Nītimañjarī [e1002n.nrf.html.txt]"],
    "e1009n.nrf.html.txt": ["197", "Añña > Nīti-gantha-saṅgaho > Naradakkhadīpanī", "Añña > Nīti-gantha-saṅgaho > Naradakkhadīpanī [e1009n.nrf.html.txt]"],
    "e1010n.nrf.html.txt": ["198", "Añña > Nīti-gantha-saṅgaho > Caturārakkhadīpanī", "Añña > Nīti-gantha-saṅgaho > Caturārakkhadīpanī [e1010n.nrf.html.txt]"],
    "e1008n.nrf.html.txt": ["199", "Añña > Nīti-gantha-saṅgaho > Cāṇakyanīti", "Añña > Nīti-gantha-saṅgaho > Cāṇakyanīti [e1008n.nrf.html.txt]"],
    "e1101n.nrf.html.txt": ["200", "Añña > Pakiṇṇaka-gantha-saṅgaho > Rasavāhinī", "Añña > Pakiṇṇaka-gantha-saṅgaho > Rasavāhinī [e1101n.nrf.html.txt]"],
    "e1102n.nrf.html.txt": ["201", "Añña > Pakiṇṇaka-gantha-saṅgaho > Sīmavisodhanīpāṭha", "Añña > Pakiṇṇaka-gantha-saṅgaho > Sīmavisodhanīpāṭha [e1102n.nrf.html.txt]"],
    "e1103n.nrf.html.txt": ["202", "Añña > Pakiṇṇaka-gantha-saṅgaho > Vessantaragīti", "Añña > Pakiṇṇaka-gantha-saṅgaho > Vessantaragīti [e1103n.nrf.html.txt]"],
    "e1201n.nrf.html.txt": ["203", "Añña > Sihaḷa-gantha-saṅgaho > Moggallāna vuttivivaraṇapañcikā", "Añña > Sihaḷa-gantha-saṅgaho > Moggallāna vuttivivaraṇapañcikā [e1201n.nrf.html.txt]"],
    "e1202n.nrf.html.txt": ["204", "Añña > Sihaḷa-gantha-saṅgaho > Thūpavaṃsa", "Añña > Sihaḷa-gantha-saṅgaho > Thūpavaṃsa [e1202n.nrf.html.txt]"],
    "e1203n.nrf.html.txt": ["205", "Añña > Sihaḷa-gantha-saṅgaho > Dāṭhāvaṃsa", "Añña > Sihaḷa-gantha-saṅgaho > Dāṭhāvaṃsa [e1203n.nrf.html.txt]"],
    "e1204n.nrf.html.txt": ["206", "Añña > Sihaḷa-gantha-saṅgaho > Dhātupāṭhavilāsiniyā", "Añña > Sihaḷa-gantha-saṅgaho > Dhātupāṭhavilāsiniyā [e1204n.nrf.html.txt]"],
    "e1205n.nrf.html.txt": ["207", "Añña > Sihaḷa-gantha-saṅgaho > Dhātuvaṃsa", "Añña > Sihaḷa-gantha-saṅgaho > Dhātuvaṃsa [e1205n.nrf.html.txt]"],
    "e1206n.nrf.html.txt": ["208", "Añña > Sihaḷa-gantha-saṅgaho > Hatthavanagallavihāravaṃsa", "Añña > Sihaḷa-gantha-saṅgaho > Hatthavanagallavihāravaṃsa [e1206n.nrf.html.txt]"],
    "e1207n.nrf.html.txt": ["209", "Añña > Sihaḷa-gantha-saṅgaho > Jinacaritaya", "Añña > Sihaḷa-gantha-saṅgaho > Jinacaritaya [e1207n.nrf.html.txt]"],
    "e1208n.nrf.html.txt": ["210", "Añña > Sihaḷa-gantha-saṅgaho > Jinavaṃsadīpaṃ", "Añña > Sihaḷa-gantha-saṅgaho > Jinavaṃsadīpaṃ [e1208n.nrf.html.txt]"],
    "e1209n.nrf.html.txt": ["211", "Añña > Sihaḷa-gantha-saṅgaho > Telakaṭāhagāthā", "Añña > Sihaḷa-gantha-saṅgaho > Telakaṭāhagāthā [e1209n.nrf.html.txt]"],
    "e1210n.nrf.html.txt": ["212", "Añña > Sihaḷa-gantha-saṅgaho > Milidaṭīkā", "Añña > Sihaḷa-gantha-saṅgaho > Milidaṭīkā [e1210n.nrf.html.txt]"],
    "e1211n.nrf.html.txt": ["213", "Añña > Sihaḷa-gantha-saṅgaho > Padamañjarī", "Añña > Sihaḷa-gantha-saṅgaho > Padamañjarī [e1211n.nrf.html.txt]"],
    "e1212n.nrf.html.txt": ["214", "Añña > Sihaḷa-gantha-saṅgaho > Padasādhanaṃ", "Añña > Sihaḷa-gantha-saṅgaho > Padasādhanaṃ [e1212n.nrf.html.txt]"],
    "e1213n.nrf.html.txt": ["215", "Añña > Sihaḷa-gantha-saṅgaho > Saddabindupakaraṇaṃ", "Añña > Sihaḷa-gantha-saṅgaho > Saddabindupakaraṇaṃ [e1213n.nrf.html.txt]"],
    "e1214n.nrf.html.txt": ["216", "Añña > Sihaḷa-gantha-saṅgaho > Kaccāyanadhātumañjusā", "Añña > Sihaḷa-gantha-saṅgaho > Kaccāyanadhātumañjusā [e1214n.nrf.html.txt]"],
    "e1215n.nrf.html.txt": ["217", "Añña > Sihaḷa-gantha-saṅgaho > Sāmantakūṭavaṇṇanā", "Añña > Sihaḷa-gantha-saṅgaho > Sāmantakūṭavaṇṇanā [e1215n.nrf.html.txt]"],
}